### ISSUE TITLE
2019.11.20关于更新及网卡咨询

### ISSUE THREAD

**Issue by Guanzj** [AsahiHuang/ThinkPad-P51-Hackintosh-Mojave#2]
hi，老哥你好，我是从GitHub看到您发的关于p51的黑苹果教程来的。非常感谢你的分享帮助我们节省了大量精力和学习成本，现阶段有3个问题想和您请教一下。
①您在GitHub之后是否有新的更新
②关于无线网卡这快您有具体的型号推荐么（我之前预估用usbwifi但是估计不理想）
③从使用体验您觉得15.1和14.6哪款更具有使用性

非常感谢！

因为电报无法向您直接发送信息故来此提交issues

**Comment by Guanzj** [comment]
关于我之前留的信息，经过实测确实15.1会好用一些，唯一缺点是ss暂时不支持15.1，

网卡考察之后认为dw1820会性价比稍高，有部分实测成功案例

**Comment by AsahiKou** [comment]
已在 [Blog](https://blog.asahih.com/Thinkpad-P51-Hackintosh/) 回复您的相关问题，Catalina 可参考[ThinkPadP51-Hackintosh-Catalina](https://github.com/AsahiHuang/ThinkPadP51-Hackintosh-Catalina)
